import Link from "next/link";
import type { AboutContent } from "@/lib/about-content";

export default function AboutPageView({ content }: { content: AboutContent }) {
  return <main>
    <section className="hero-band" style={{ "--hero-image": `url('${content.hero.image.src}')` } as React.CSSProperties}><div className="hero-in"><h1>{content.hero.heading}</h1></div></section>
    <section className="section"><div className="wrap"><span className="eyebrow">{content.overview.eyebrow}</span><div className="eyebrow-rule" style={{ background: "var(--black)" }} /><p className="intro-bold">{content.overview.intro}</p><div className="about-stats" aria-label="Kasumigaseki MENA company overview">{content.overview.metrics.map((metric) => <div className="about-stat" key={metric.label}><strong>{metric.value}</strong><span>{metric.label}</span></div>)}</div><div className="about-stat-source"><a href="https://kasumigaseki.co.jp/en/ir/" target="_blank" rel="noopener">As of February 28, 2026</a></div><div className="about-biz">{content.overview.businessLines.map((line, index) => <div className="biz-row" key={line.title}><div className="biz-num">{String(index + 1).padStart(2, "0")}</div><div><div className="biz-title">{line.title}</div><p className="biz-desc">{line.description}</p></div></div>)}</div><div className="about-cta"><Link href={content.overview.action.href} className="btn btn-solid">{content.overview.action.label} <span aria-hidden="true">→</span></Link></div></div></section>
    <section className="section ceo-section"><div className="wrap"><div className="ceo-grid"><div className="ceo-photo"><img src={content.chairman.image.src} alt={content.chairman.image.alt} loading="lazy" /></div><div className="ceo-body"><span className="eyebrow">{content.chairman.eyebrow}</span><div className="eyebrow-rule" style={{ background: "var(--black)" }} /><p className="ceo-lead">“{content.chairman.quote}”</p><div className="ceo-text">{content.chairman.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div><div className="ceo-sign"><div className="name">{content.chairman.name}</div><div className="title">{content.chairman.title}</div></div></div></div></div></section>
    <section className="vm-dark"><div className="wrap"><div className="vm-dark-grid">{content.visionMission.map((item) => <div className="vm-dark-col" key={item.eyebrow}><span className="eyebrow">{item.eyebrow}</span><div className="eyebrow-rule" /><p className="vm-quote">“{item.quote}”</p><cite className="vm-cite">— {item.attribution}</cite></div>)}</div></div></section>
    <section className="phil-section"><div className="wrap"><div className="phil-grid">{content.principles.map((item) => <div className="phil-col" key={item.eyebrow}><span className="eyebrow">{item.eyebrow}</span><div className="eyebrow-rule" /><div className="phil-title">{item.title}</div><p className="phil-text">{item.body}</p></div>)}</div></div></section>
  </main>;
}
