"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
type Project = { id:number; name:string; slug:string; sector:string; status:string; location:string|null; summary:string|null; description:string|null; images:string[]|null; sort_order:number };
export default function ProjectEditor({ project }: { project: Project | null }) {
 const router=useRouter(); const [error,setError]=useState(""); const [saving,setSaving]=useState(false);
 async function save(e:FormEvent<HTMLFormElement>) { e.preventDefault(); setSaving(true); setError(""); const f=new FormData(e.currentTarget); const payload={name:f.get("name"),slug:f.get("slug"),sector:f.get("sector"),status:f.get("status"),location:f.get("location"),summary:f.get("summary"),description:f.get("description"),sort_order:Number(f.get("sort_order")||0),images:String(f.get("images")||"").split(/\n/).map(x=>x.trim()).filter(Boolean)}; try { const r=await fetch(project?`/api/projects/${project.id}`:"/api/projects",{method:project?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}); const d=await r.json(); if(!r.ok) throw new Error(d.error); router.push("/admin/projects"); router.refresh(); } catch(err){setError(err instanceof Error?err.message:"Save failed");} finally{setSaving(false);} }
 async function remove(){if(!project||!confirm(`Delete "${project.name}"?`))return; const r=await fetch(`/api/projects/${project.id}`,{method:"DELETE"}); if(r.ok){router.push("/admin/projects");router.refresh();}else setError("Could not delete project");}
 const label={display:"block",fontSize:".72rem",fontWeight:700,textTransform:"uppercase" as const,letterSpacing:".06em",marginBottom:5,color:"var(--grey-5)"}; const field=(name:string,labelText:string,type="text")=><div style={{marginBottom:16}}><label htmlFor={name} style={label}>{labelText}</label><input id={name} name={name} type={type} defaultValue={(project?.[name as keyof Project] as string|number|null)??""}/></div>;
 return <form onSubmit={save} className="card" style={{maxWidth:800}}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}>{field("name","Project name")}{field("slug","Slug")}</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 120px",gap:16,marginBottom:16}}><div><label style={label}>Sector</label><select name="sector" defaultValue={project?.sector??"real-estate"}>{["real-estate","real-estate-development","f-and-b","local-business","global-businesses"].map(x=><option key={x}>{x}</option>)}</select></div><div><label style={label}>Status</label><select name="status" defaultValue={project?.status??"draft"}><option value="draft">Draft</option><option value="published">Published</option></select></div>{field("sort_order","Order","number")}</div>{field("location","Location")}<div style={{marginBottom:16}}><label style={label}>Summary</label><textarea name="summary" rows={3} defaultValue={project?.summary??""}/></div><div style={{marginBottom:16}}><label style={label}>Description</label><textarea name="description" rows={10} defaultValue={project?.description??""}/></div><div style={{marginBottom:16}}><label style={label}>Image URLs (one per line)</label><textarea name="images" rows={4} defaultValue={project?.images?.join("\n")??""}/></div><div style={{display:"flex",gap:10}}><button className="btn btn-dark" disabled={saving}>{saving?"Saving…":"Save Project"}</button><button type="button" className="btn" onClick={()=>router.push("/admin/projects")}>Cancel</button>{project&&<button type="button" className="btn btn-danger" onClick={remove}>Delete</button>}</div>{error&&<p className="error-msg">{error}</p>}</form>;
}
