/**
 * Extracts the legal content (meta + body) from the delivered static pages and
 * generates db/seed-pages.sql so the Next.js routes serve identical content.
 *
 * Run from the repo root:  node scripts/extract-legal.mjs
 * Output: db/seed-pages.sql (ON CONFLICT DO NOTHING — never overwrites admin edits)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const SLUGS = ["privacy-policy", "terms-and-conditions", "cookie-policy", "legal-notice"];

function extract(slug) {
  const html = readFileSync(join(process.cwd(), "public", slug, "index.html"), "utf8");

  const title = html.match(/<section class="legal-hero">[\s\S]*?<h1>([\s\S]*?)<\/h1>/)?.[1]?.trim() ?? slug;
  const meta = html.match(/<aside class="legal-meta">([\s\S]*?)<\/aside>/)?.[1]?.trim() ?? "";
  const body = html.match(/<div class="legal-body">([\s\S]*?)\s*<\/div>\s*<\/div>\s*<\/section>/)?.[1]?.trim();
  const description = html.match(/<meta name="description" content="([\s\S]*?)">/)?.[1] ?? "";

  if (!body) throw new Error(`Could not extract .legal-body from ${slug}`);
  if (/\$page\$/.test(body)) throw new Error(`${slug} contains the SQL dollar-quote delimiter`);

  return { title, description, content: { meta, body } };
}

const rows = SLUGS.map((slug) => {
  const { title, description, content } = extract(slug);
  const seo = JSON.stringify({ title: `${title} | Kasumigaseki MENA`, description });
  return `('${slug}', $page$${title}$page$, 'published', $page$${JSON.stringify(content)}$page$::jsonb, $page$${seo}$page$::jsonb)`;
});

const sql = `-- Legal pages seed: content extracted verbatim from the delivered static pages
-- (${SLUGS.join(", ")}).
-- Generated by scripts/extract-legal.mjs. Re-runnable: existing rows are never
-- overwritten, so admin edits made in the CMS are always preserved.
INSERT INTO pages (slug, title, status, content, seo)
VALUES
${rows.join(",\n")}
ON CONFLICT (slug) DO NOTHING;
`;

writeFileSync(join(process.cwd(), "db", "seed-pages.sql"), sql, "utf8");
console.log(`Wrote db/seed-pages.sql with ${rows.length} pages.`);
for (const s of SLUGS) {
  const { title } = extract(s);
  console.log(`  - ${s}: "${title}"`);
}
